import mongoose from "mongoose";

// No object storage (S3/Cloudinary/CDN) is integrated anywhere in this
// project — same honest-stub pattern as Phase 12's ReviewMedia: real model,
// real validation (MIME/size limits enforced in mediaService.js), but
// `url`/`storageKey` are supplied by the caller rather than generated by
// an actual upload pipeline. This is the seam a real storage integration
// would slot into later.
const mediaAssetSchema = new mongoose.Schema(
  {
    filename: { type: String, required: true },
    type: { type: String, enum: ["image", "video", "document"], required: true },
    url: { type: String, required: true },
    storageKey: String,
    mimeType: String,
    size: Number, // bytes
    width: Number,
    height: Number,
    altText: String, // rule #52 — encouraged/required for important images, enforced at publish-validation time, not at upload time
    caption: String,
    uploadedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    status: { type: String, enum: ["ready", "archived"], default: "ready" },
  },
  { timestamps: true }
);

mediaAssetSchema.index({ type: 1, status: 1 });
mediaAssetSchema.index({ createdAt: -1 });

export default mongoose.model("MediaAsset", mediaAssetSchema);
