import mongoose from "mongoose";

// No object storage (S3/Cloudinary/etc.) is integrated anywhere in this
// project — same "structural, not faked" honesty as Phase 8's Stripe stub
// and Phase 10's Shiprocket stub. This model and the presigned-upload-shaped
// flow in reviewMediaService.js are real and enforce real limits/validation,
// but `url`/`storageKey` are supplied by the caller rather than generated by
// an actual storage backend — the seam is exactly where a real
// S3-presigned-URL integration would slot in later without changing this
// schema or reviewService's calling code.
const reviewMediaSchema = new mongoose.Schema(
  {
    review: { type: mongoose.Schema.Types.ObjectId, ref: "Review", required: true },
    type: { type: String, enum: ["image", "video"], required: true },
    url: { type: String, required: true },
    storageKey: String,
    mimeType: String,
    size: Number, // bytes
    width: Number,
    height: Number,
    duration: Number, // seconds, video only
    status: { type: String, enum: ["uploading", "processing", "ready", "rejected"], default: "ready" },
  },
  { timestamps: true }
);

reviewMediaSchema.index({ review: 1 });

export default mongoose.model("ReviewMedia", reviewMediaSchema);
